---
title: "Minicursos e Palestras"
---
***

## Machine Learning no Pycaret com dados do Covid-19

Minicurso de Modelos de Regressão e Séries Temporais oferecido através do grupo de extensão PREDICT, .

<iframe width="560" height="315" src="https://www.youtube.com/embed/nh-kSc7keJ4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Material do curso: https://predict-icmc.github.io/pycaret-covid19/


##### Palavras-chave: `python`, `machine learning`, `covid-19`, `modelos de regressão`, `séries temporais`

***


## Visualização de dados geolocalizados com o R-Shiny


Minicurso oferecido através do grupo de extensão PREDICT aos alunos do Bacharelado em Estatística e Ciência de Dados do ICMC-USP, e disponibilizado no Youtube.

<iframe width="560" height="315" src="https://www.youtube.com/embed/25ND51icjIw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Material do curso: https://predict-icmc.github.io/curso-shiny/


##### Palavras-chave: `R`, `shiny`, `covid-19`, `visualização de dados`, `geolocalização`

***

## A dispersão aleatória auxilia na sobrevivência?

Palestra sobre modelos de nascimento e morte em Processos Estocásticos, que explica como modelos com dispersão aleatória dos indivíduos podem auxiliar em sua sobrevivência.

<iframe width="560" height="315" src="https://www.youtube.com/embed/Q1_tBZmXriE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


##### Palavras-chave: `R`, `processos estocásticos`, `processos de nascimento e morte`, `modelos de dispersão aleatória`, `cadeias de Markov`

***
